---

- name: 'Add Keys'
  include_tasks: 'key.yml'

- name: 'Install nessesary package'
  include_tasks: 'packages.yml'

- name: 'Add Apt Repo'
  include_tasks: 'apt.yml'

- name: 'Install erlang packages'
  include_tasks: 'erlang.yml'

- name: 'Install RabbitMQ Server'
  include_tasks: 'rabbit.yml'